# --------------------------------------------- HYDRA -----------------------------------------------------
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:  
    dir: .

# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  save_video : False  # Сохранение итогового видео обработки
  
#--------------------------------------------------GENERAL--------------------------------------------------

general:
  colors_of_roads: # in bgr
    1: [102,204,255] #ffcc66
    2: [0,0,102] #660000
    3: [17,70,10] #0a3e11
    4: [120,56,126] #7e3878
    5: [30,105,215] #d2691e


# ------------------------------------------------- NODES --------------------------------------------------

video_reader:
  src: test_videos/test_video.mp4  # путь до файла обработки или номер камеры
  skip_secs : 0  # считываем кадры раз в <skip_secs> секунд
  roads_info: configs/entry_exit_lanes.json  # json файл с координатами дорог на видео


detection_node:
  weight_pth: weights/yolov8m.pt
  classes_to_detect: [2,3,5,7]  # весь транспорт из классов COCO
  confidence: 0.15  # Порог уверенности детектора (чем больше значение, тем меньше находит)
  iou: 0.7  # Порог NMS (чем больше значение, тем больше находит)
  imgsz: 640  # Ресайз при инференсе (640 по умолчанию)


tracking_node:  
  # Использован ByteTrack (https://github.com/ifzhang/ByteTrack)
  first_track_thresh: 0.7  # Пороговое значение для первичной инициализации трека
  second_track_thresh: 0.20  # Пороговое значение для поддержания трека
  match_thresh: 0.4  # Чем меньше значение, тем больше может быть расстояние между соседними обнаруженими чтобы держать трек
  track_buffer: 60  # Время жизни трека после исчезновения из поля зрения (измеряется в числе кадров)


show_node:
  scale : 0.7  # Масштабирование итогового окна результатов при imshow=True
  fps_counter_N_frames_stat : 15  # Окно усредения fsp счетчика
  draw_fps_info : True  # Указывать ли fps обработки
  show_roi: True  # Показывать ли регионы примыкающих дорог 
  overlay_transparent_mask: True # Заливка регионов при show_roi=True (медленная операция)
  graph_pose: right # Где результаты расположить снизу или справа (down, right)
  imshow: True  # Нужно ли выводить видео в процессе обработки


video_saver_node:
  fps : 30  # при увеличении позволяет ускорить итоговое видео
  out_folder : test_videos/videos_out  # в какую папку сохранить результат

